// RUN: ./build/qparse %s --emit-mlir | ./build/quantum-opt --verify-diagnostics --quantum-verify-no-cloning

// This file is an end-to-end integration test.
// It pipes the raw MLIR generated by the frontend directly into the
// MLIR diagnostic verifier to mathematically prove that the generated
// IR contains no leaks, no cloning violations, and has valid types.

OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
creg c[1];
h q[0];
cx q[0], q[1];
measure q[0] -> c[0];
